### ISSUE TITLE
More message customisation

### ISSUE THREAD

**Issue by OfficialTheosis** [Jochyoua/SafeChatX#1]
## Detailed Description

We should be able to customise more messages, particularly the "You are missing permission" message.
## Context
I would like it to be consistent with all of the other "no permission" messages I have on my server. I'm sure this could benefit other users in the same way.
## Your Environment

* Plugin version used: 2.1.8-SNAPSHOT
* Java version (e.g. Java 8 or Java 11/16): 16
* Server type and version: Paper-170 (MC: 1.17.1)
* Operating System and version: Windows 10

**Comment by Jochyoua** [comment]
You should be able to edit that message and others by customizing the locale configurations. You can find more information here:
https://github.com/Jochyoua/SafeChatX/wiki/Localization-Configuration, you are looking to modify missing_permission

**Comment by OfficialTheosis** [comment]
> You should be able to edit that message and others by customizing the locale configurations. You can find more information here:
> https://github.com/Jochyoua/SafeChatX/wiki/Localization-Configuration, you are looking to modify missing_permission

Ah, sorry I must have missed this. It works, cheers!
