### ISSUE TITLE
Handle cancelled chat events

### ISSUE THREAD

**Issue by OfficialTheosis** [Jochyoua/SafeChatX#2]
## Detailed Description
Basically, SafeChat would handle chat events even if they are cancelled by another plugin.

## Context
The reason this might be useful for me and others is because plugins that utilise their own kind of "chat channel", such as plot chat, gang chat or staff chat, usually work by cancelling regular chat events and taking the message from them and handling them in their own way. This makes it so that SafeChat is unable to affect these "chat channels" (at least that's what I think is going on).

## Possible Implementation
Handle chat events regardless of whether or not they have been cancelled (assuming what I explained above is how it all works).

## Your Environment
* Plugin version used: 2.1.8-SNAPSHOT
* Java version (e.g. Java 8 or Java 11/16): 16
* Server type and version: Paper-182 (MC: 1.17.1)
* Operating System and version: Windows 10

**Comment by Jochyoua** [comment]
Will be added in 2.1.9-SNAPSHOT, for reference: f9d76e7
